- pom.xml
Synchronize version number with GitHub release version numbers
> Update version from 0.0.1-SNAPSHOT to 1.3.0

- pom.xml
chore: bump spring-boot-starter-parent 2.3.0-RELEASE to 2.3.3
> chore: bump version 1.3.0 to 1.3.1

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
> feat: added GitHub templates.

- .travis.yml
> Update Travis config: deploy to PyPi on tag

- setup.py
See https://pypi.org/classifiers/
-
-
> Fix setup license classifier

- setup.py
> Bump version 2.0.1 to 3.0.0rc0

- setup.py
> Fix setup: add long_description_content_type

- .travis.yml
- Travis regex for pypi deployment and auto release
-
> Fixed Travis regex for release and pypi deployment

- .travis.yml
> Fix Travis GitHub releases deploy: do not upload assets

- src/molgenis/capice/cli/args_handler_parent.py
- src/molgenis/capice/cli/args_handler_predict.py
- src/molgenis/capice/utilities/input_processor.py
- tests/capice/utilities/test_input_processor.py
- Fixed a bug when no output was given through the CLI, the output (if exists) would be overwritten.
Closes #86
- [later as part of #88] Functionality works & meets specs
- [n.a.] Documentation was updated
> fix: auto overwrite

- src/molgenis/capice/main_predict.py
- src/molgenis/capice/validators/post_file_parse_validator.py
- Fixed a bug where feature "feature_type"  was not checked upon loading in the input dataset in the predict mode.
- Closes #102
- Once both #104 and #105 have been merged, CAPICE 3.1.1 can be released.
> fix: Fixed required feature bug

- .travis.yml
- README.md
- Renamed primary branch to main instead of master within Travis CI.
- The primary branch should be renamed to main.
> chore: Primary branch rename

- src/molgenis/capice/main_train.py
- Added a INFO level log of all the features that are going to be used in training.
- Closes #128
> feat: Informative train info log

- README.md
> README updates: Added info about Singularity image and added section with original sources data

- src/molgenis/capice/core/capice_exporter.py
- tests/capice/core/test_capice_exporter.py
- tests/capice/test_main_predict.py
> Fixed a bug that would force the predict output file to always be gzipped

- setup.py
> Updated xgboost to 1.7.3

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- scripts/convert_vep_vcf_to_tsv_capice.sh
- setup.py
- Changed the dependency of "BCFTools" to be installed to "apptainer" .
- Changed the working of the conversion script to now work with apptainer.
- Small QoL github templates improvements.
- Updated github templates [edit by @svandenhoek]
-
> Feat/easybuild to apptainer + README/setupy.py adjustments

- setup.py
- Updated CAPICE dependencies to latest and greatest direct dependencies.
- 
- This is done together with CAPICE-resources to equalize the dependency versions between the 2 repositories.
- [All tests pass] Functionality works & meets specs
- [N.A.] Documentation was updated
> chore: Update and equalize dependencies

- src/molgenis/capice/main_explain.py
- Added #154 fix for explain tool.
-
> Fixed a bug that would force the predict output file to always be gzipped (explain)

- README.md
- scripts/convert_vep_vcf_to_tsv_capice.sh
- Added -b flag to the bash script to pipe apptainer --bind path(s) to prevent manual editing of the bash script.
- New release isn't necessairy since this is not a change to the python CAPICE source code.
> feat: Bind flag pipe through to apptainer

- README.md
> Update Requirements section
